server:
  servlet:
    context-path: /student
  port: 8080


spring:
  profiles.active: local

---
azure:
 cosmosdb: 
   uri: https://localhost:8081
   key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
   database: azurecosmosdb


info:
  app:
   name:@project.name@